export { default as HeroView } from './hero/HeroView'
export { default as BrandGalleryView } from './showcase/BrandGalleryView'
export { default as CollectItAllView } from './showcase/CollectItAllView'
export { default as LatestReleasesView } from './features/LatestReleasesView'
export { default as RecommendedView } from './features/RecommendedView'
// export { default as ProductCarouselView } from './showcase/ProductCarouselView'
